name-template: "Recent Activity v$RESOLVED_VERSION Released!"
tag-template: "v$RESOLVED_VERSION"
prerelease: false
publish: false
exclude-labels:
  - "skip-changelog"
categories:
  - title: "🚀 Features"
    labels:
      - "Type: enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "Type: bug"
  #- title: "⚡ Performance Improvements"
  #  labels:
  #    - "performance"
  - title: "📖 Docs"
    labels:
      - "Updates: documentation"
  #- title: "🏭 Installation"
  #  labels:
  #    - "install"
  - title: "🔧 Chores"
    labels:
      - "Updates: dependencies"
      - "Updates: github action"
autolabeler:
  - label: "Updates: documentation"
    files:
      - "*.md"
  - label: "Updates: github action"
    files:
      - ".github/workflows/*.yml"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Release Notes
  $CHANGES

  ## Thanks to
  $CONTRIBUTORS
