name-template: "Recent Activity v$RESOLVED_VERSION Released!"
tag-template: "v$RESOLVED_VERSION"
commitish: main
publish: false
exclude-labels:
  - "Updates: github action"
  - "No changelog"
  - "Updates: documentation"

category-template: "### $TITLE"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "Type: breaking"
  - title: "🚀 Features"
    labels:
      - "Type: enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "Type: bug"
  - title: "🔧 Chores"
    labels:
      - "Updates: dependencies"

autolabeler:
  - label: "Updates: documentation"
    files:
      - "README.md"
      - "CHANGELOG.md"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Release Notes
  $CHANGES

  ## Thanks to
  $CONTRIBUTORS
