name-template: "Recent Activity v$RESOLVED_VERSION Released!"
tag-template: "v$RESOLVED_VERSION"
prerelease: false
publish: false
exclude-labels:
  - "skip-changelog"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "fix"
      - "bug"
  - title: "⚡ Performance Improvements"
    labels:
      - "performance"
  - title: "📖 Docs"
    labels:
      - "documentation"
      - "docs"
  - title: "🏭 Installation"
    labels:
      - "install"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Release Notes
  $CHANGES
