name: Recent GitHub Activity - Profile Readme
description: Add your recent activity to your profile readme!
author: jamesgeorge007, abhijoshi2k, PuneetGopinath

inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing the file"
    default: ":zap: Update README with the recent activity"
    required: false
  MAX_LINES:
    description: "The maximum number of lines populated in your README.md file"
    default: 5
    required: false
  README_FILE:
    description: "Path to your README.md file"
    default: "./README.md"
    required: false

  DISABLE_COMMENTS:
    description: "Do you want to disable comments?"
    default: false
    required: false
  DISABLE_ISSUES:
    description: "Do you want to disable issues?"
    default: false
    required: false
  DISABLE_PR:
    description: "Do you want to disable pull request events?"
    default: false
    required: false

  # COMMENTS
  COMMENTS_ACTIVITY:
    description: "How the comments activity should be printed."
    default: "🗣 Commented on {ID} in {REPO}"
    required: false

  # ISSUES
  ISSUE_OPENED:
    description: "How the 'issue opened' activity should be printed."
    default: "❗️ Opened issue {ID} in {REPO}"
    required: false
  ISSUE_CLOSED:
    description: "How the 'issue closed' activity should be printed."
    default: "❗️ Closed issue {ID} in {REPO}"
    required: false

  # PR
  PR_OPENED:
    description: "How the 'pull request opened' activity should be printed."
    default: "💪 Opened PR {ID} in {REPO}"
    required: false
  PR_CLOSED:
    description: "How the 'pull request closed' activity should be printed."
    default: "❌ Closed PR {ID} in {REPO}"
    required: false
  PR_MERGED:
    description: "How the 'pull request merged' activity should be printed."
    default: "🎉 Merged PR {ID} in {REPO}"
    required: false

branding:
  color: orange
  icon: activity

runs:
  using: node12
  main: dist/index.js
