name: Recent GitHub Activity - Profile Readme
description: Add your recent activity to your profile readme!
author: jamesgeorge007, abhijoshi2k, PuneetGopinath

inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing the file"
    default: ":zap: Update README with the recent activity"
    required: false
  MAX_LINES:
    description: "The maximum number of lines populated in your README.md file"
    default: 5
    required: false
  README_FILE:
    description: "Path to your README.md file"
    default: "./README.md"
    required: false

  # COMMENTS
  COMMENTS_ACTIVITY:
    description: "How the comments activity should be printed."
    default: "🗣 Commented on {ID} in {REPO}"
    required: false

branding:
  color: orange
  icon: activity

runs:
  using: node12
  main: dist/index.js
