name: Recent GitHub Activity - Profile Readme
description: Add your recent activity to your profile readme!
author: jamesgeorge007, abhijoshi2k, PuneetGopinath, Andre601

inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  CONFIG_FILE:
    description: "Path to configuration file"
    default: "./.github/recent-activity.config.yml"
    required: false

branding:
  color: orange
  icon: activity

runs:
  using: node12
  main: dist/index.js
